#!/bin/bash -l

#SBATCH -A standby
#SBATCH --nodes=1
#SBATCH --ntasks=5
#SBATCH -n 20
#SBATCH --mem-per-cpu=5G
#SBATCH --time=4:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=ddeemer@purdue.edu

cd /scratch/snyder/d/ddeemer/WhiteRed

# Step 1: Load required modules:

module load bioinfo
module load MaxBin/2.2.3


#Step 2: Run the program
# Bin contigs based on tetranucleotide frequency and contig coverages

# A.) Bin with W1 BT2 Default mapped abundances
#time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/W1Cont_W1Map -reads FASTQ/043948_W12-D7_R1_filtered.fastq -reads2 FASTQ/043948_W12-D7_R2_filtered.fastq

# B.) Bin with W1 BWA mapped abundances obtained from pileup.sh
#time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/W1Cont_W1Map_BWAabund -abund Abundance_Files/abundance01.txt

# C.) Bin with All BWA mapped abundances obtained from pileup.sh
#time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/W1Cont_AllMap -abund_list Abundance_Files/abund_list.txt

# D.) Bin as in 'B', except BT2 abundances from 99% identity
time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/BT2_99F_W1 -abund Abundance_Files/BT2_99F_Abunds/abundance01_BT2_99F.txt

# E.) Bin as in 'C', except BT2 abundances from 99% identity
time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/BT2_99F_All -abund_list Abundance_Files/BT2_99F_Abunds/abund_list_99F.txt

# F.) Bin with All BT2 Default mapped abundances
time run_MaxBin.pl -contig assembly_metaSpades/W1.contigs.fasta -out MaxBin_Results/BT2_All -abund_list Abundance_Files/BT2_Abunds/abund_list_BT2.txt
